# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-26 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('carmake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankcars.CarMake')),
            ],
        ),
        migrations.CreateModel(
            name='CarYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('carmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankcars.CarModel')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='carmake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankcars.CarMake'),
        ),
        migrations.AddField(
            model_name='car',
            name='carmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankcars.CarModel'),
        ),
        migrations.AddField(
            model_name='car',
            name='caryear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankcars.CarYear'),
        ),
    ]
